### ISSUE TITLE
Feature request: `const fn` support

### ISSUE THREAD

**Issue by korken89** [frewsxcv/rust-gcd#8]
Hi,

Thanks for this minimal lib!
I'd like to make a feature request, to move the implementations to `const fn` and have the trait call the `const fn` methods.
This would allow for compile time finding of GCD values.

**Comment by TDHolmes** [comment]
I think all that is needed is to either wait for [`const_swap`](https://github.com/rust-lang/rust/issues/83163) or just do it ourselves with a temp variable
